color                               = "Auto"
ignore                              = []
edition                             = "2024"
emit_mode                           = "Files"
hard_tabs                           = false
max_width                           = 100
tab_spaces                          = 4
array_width                         = 60
brace_style                         = "PreferSameLine"
chain_width                         = 60
make_backup                         = false
indent_style                        = "Block"
comment_width                       = 80
fn_call_width                       = 60
group_imports                       = "Preserve"
merge_derives                       = true
newline_style                       = "Auto"
skip_children                       = false
style_edition                       = "2024"
wrap_comments                       = false
fn_single_line                      = true
format_strings                      = true
imports_indent                      = "Block"
imports_layout                      = "HorizontalVertical"
trailing_comma                      = "Vertical"
binop_separator                     = "Front"
reorder_imports                     = true
reorder_modules                     = true
fn_params_layout                    = "Tall"
hex_literal_case                    = "Preserve"
match_arm_blocks                    = true
required_version                    = "1.8.0"
struct_lit_width                    = 18
show_parse_errors                   = true
space_after_colon                   = true
unstable_features                   = false
use_try_shorthand                   = true
where_single_line                   = true
attr_fn_like_width                  = 70
force_explicit_abi                  = true
normalize_comments                  = true
reorder_impl_items                  = false
space_before_colon                  = false
trailing_semicolon                  = true
control_brace_style                 = "AlwaysSameLine"
format_macro_bodies                 = true
imports_granularity                 = "Preserve"
combine_control_expr                = false
error_on_unformatted                = false
spaces_around_ranges                = true
struct_variant_width                = 35
use_small_heuristics                = "Default"
disable_all_formatting              = false
empty_item_single_line              = true
error_on_line_overflow              = false
force_multiline_blocks              = true
format_generated_files              = true
inline_attribute_width              = 0
struct_lit_single_line              = true
blank_lines_lower_bound             = 0
blank_lines_upper_bound             = 1
match_arm_leading_pipes             = "Never"
overflow_delimited_expr             = false
normalize_doc_attributes            = false
type_punctuation_density            = "Wide"
use_field_init_shorthand            = false
condense_wildcard_suffixes          = true
match_block_trailing_comma          = false
doc_comment_code_block_width        = 100
struct_field_align_threshold        = 0
single_line_if_else_max_width       = 50
short_array_element_width_threshold = 10
