name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Build
        run: cargo build --verbose
      - name: Run Clippy
        run: cargo clippy --verbose
      - name: Run Tests
        run: cargo test --verbose
      - name: Install Audit
        run: cargo install cargo-audit
      - name: Run Audit
        run: cargo audit --deny warnings
      - name: Install Formatting nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-03-01
          components: rustfmt
      - name: Run Formatting check
        run: cargo +nightly fmt --check --verbose
      - name: Install MSRV
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          override: true
      - name: Run MSRV
        run: cargo build
